<a href="https://colab.research.google.com/github/infamous001/acm_project/blob/main/logistic_regression(self_implemented).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [94]:
dataset=pd.read_csv("IRIS.csv")
dataset.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [95]:
x=dataset.iloc[:,:-1].values
yoriginal=dataset.iloc[:,-1].values

In [96]:
print(x[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [97]:
print(yoriginal[:5])

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [98]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
y = np.array(ct.fit_transform(yoriginal.reshape(len(yoriginal),-1)))

In [99]:
print(y[:5])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [100]:
def sigmoid(z):
  g=1/(1+np.exp(-z))
  return g

In [101]:
def compute_cost(X, y, w, b, lambda_= 1):
    m, n = X.shape
    
    loss_sum=0
    for i in range(m):
        z_wb=0
        loss=0
        for j in range(n):
            z_w_ij=w[j]*X[i][j]
            z_wb+=z_w_ij
        z_wb+=b
        f_wb=sigmoid(z_wb)
        loss+= -y[i] * np.log(f_wb) - (1 - y[i]) * np.log(1 - f_wb)
        loss_sum+=loss
    total_cost=(1/m)*loss_sum

    return total_cost

In [102]:
def compute_gradient(X, y, w, b, lambda_=None): 
    m, n = X.shape
    dj_dw = np.zeros(w.shape)
    dj_db = 0. 
    for i in range(m):
        z_wb = 0
        for j in range(n): 
            z_w_ij=w[j]*X[i][j]
            z_wb+=z_w_ij
        z_wb+=b
        f_wb=sigmoid(z_wb)
        
        dj_db_i = f_wb-y[i]
        dj_db += dj_db_i
        
        for j in range(n):
            dj_dw_ij = (f_wb - y[i])* X[i][j]
            dj_dw[j]+=dj_dw_ij 
            
    dj_dw = dj_dw/m
    dj_db = dj_db/m
    return dj_db,dj_dw

In [103]:
import math
def gradient_descent(X, y, w_in, b_in, cost_function, gradient_function, alpha, num_iters, lambda_): 
    m = len(X)
    
    J_history = []
    w_history = []
    
    for i in range(num_iters):
        dj_db, dj_dw = gradient_function(X, y, w_in, b_in, lambda_)   
        w_in = w_in - alpha * dj_dw               
        b_in = b_in - alpha * dj_db              

        if i<100000:  
            cost =  cost_function(X, y, w_in, b_in, lambda_)
            J_history.append(cost)

        if i% math.ceil(num_iters/10) == 0 or i == (num_iters-1):
            w_history.append(w_in)
            print(f"Iteration {i:4}: Cost {float(J_history[-1]):8.2f}   ")
        
    return w_in, b_in, J_history, w_history 

In [104]:
def predict(X, w, b): 
    m, n = X.shape   
    p = np.zeros(m)
    for i in range(m):   
        z_wb = 0
        for j in range(n): 
            z_wb_ij=w[j]*X[i][j]
            z_wb += z_wb_ij
         
        z_wb += b
        

        f_wb = float(sigmoid(z_wb))

        p[i] =f_wb
    return p

In [105]:
np.random.seed(1)
m,n=x.shape
intial_w = np.zeros(n)
initial_b = -8

iterations = 11000
alpha = 0.001

w,b, J_history,_ = gradient_descent(x ,y[:,0], intial_w, initial_b, compute_cost, compute_gradient, alpha, iterations, 0)

Iteration    0: Cost     2.66   
Iteration 1100: Cost     0.68   
Iteration 2200: Cost     0.36   
Iteration 3300: Cost     0.23   
Iteration 4400: Cost     0.17   
Iteration 5500: Cost     0.13   
Iteration 6600: Cost     0.11   
Iteration 7700: Cost     0.09   
Iteration 8800: Cost     0.08   
Iteration 9900: Cost     0.07   
Iteration 10999: Cost     0.06   


In [106]:
ypred1=predict(x,w,b)

In [107]:
print(ypred1)

[0.94933984 0.85455455 0.88445188 0.80131254 0.95167249 0.96691217
 0.88230321 0.92093943 0.71901321 0.86649541 0.97113518 0.88384188
 0.84883669 0.82779913 0.993772   0.99327844 0.98264225 0.94509241
 0.97517784 0.96157635 0.93374077 0.9505013  0.95772674 0.86056224
 0.82249998 0.82784294 0.89281971 0.94762751 0.94690088 0.82336773
 0.81603925 0.94301341 0.98303925 0.9910821  0.86649541 0.93030632
 0.9738401  0.86649541 0.78325725 0.92991921 0.94688298 0.51773999
 0.83814278 0.89376057 0.92227317 0.82570875 0.9584962  0.85064844
 0.9672506  0.91987384 0.16669611 0.10478024 0.08826668 0.01908073
 0.05216846 0.02642811 0.07507403 0.04191215 0.08169205 0.02844708
 0.01713793 0.06535548 0.03866678 0.03484991 0.112136   0.15657354
 0.02800193 0.06066047 0.01471068 0.04251267 0.02799092 0.09458564
 0.01483572 0.03451943 0.10118142 0.11982611 0.05983144 0.04266835
 0.03894557 0.11323452 0.03699324 0.04702033 0.07048623 0.00954183
 0.02171881 0.08381916 0.09407273 0.0276814  0.06204602 0.0271

In [108]:
np.random.seed(1)
m,n=x.shape
intial_w = np.zeros(n)
initial_b = -8

iterations = 11000
alpha = 0.001

w,b, J_history,_ = gradient_descent(x ,y[:,1], intial_w, initial_b, compute_cost, compute_gradient, alpha, iterations, 0)

Iteration    0: Cost     2.66   
Iteration 1100: Cost     0.74   
Iteration 2200: Cost     0.73   
Iteration 3300: Cost     0.72   
Iteration 4400: Cost     0.71   
Iteration 5500: Cost     0.71   
Iteration 6600: Cost     0.71   
Iteration 7700: Cost     0.70   
Iteration 8800: Cost     0.70   
Iteration 9900: Cost     0.70   
Iteration 10999: Cost     0.69   


In [109]:
ypred2=predict(x,w,b)

In [110]:
print(ypred2)

[0.16331549 0.12554758 0.10798657 0.10014556 0.15316725 0.22032434
 0.10143897 0.14981671 0.07910375 0.13391631 0.21815164 0.12847334
 0.11864475 0.07233764 0.29497805 0.29016191 0.2081116  0.15873598
 0.27747125 0.17034166 0.21307323 0.16257228 0.10194507 0.15119673
 0.13469157 0.1410841  0.14360106 0.17985841 0.17399796 0.11334218
 0.12122951 0.19614201 0.20574278 0.2524144  0.13391631 0.13768232
 0.22120643 0.13391631 0.07939286 0.1627748  0.14379523 0.07303738
 0.08268474 0.13807242 0.17587638 0.1117363  0.17782321 0.10050319
 0.20184796 0.14476235 0.5889871  0.42548701 0.56014379 0.19671333
 0.43235485 0.26715536 0.40754744 0.11919888 0.4790045  0.15902099
 0.12413331 0.29100805 0.30242033 0.35632312 0.22294389 0.49707677
 0.24397503 0.28827792 0.32784231 0.22885576 0.30171774 0.33035973
 0.38207164 0.36687115 0.41700369 0.46702011 0.52320241 0.49333927
 0.31867727 0.24360165 0.2053242  0.20790729 0.26740143 0.3253894
 0.2095506  0.33553962 0.50220835 0.36635547 0.24309652 0.20379

In [111]:
np.random.seed(1)
m,n=x.shape
intial_w = np.zeros(n)
initial_b = -8

iterations = 11000
alpha = 0.001

w,b, J_history,_ = gradient_descent(x ,y[:,2], intial_w, initial_b, compute_cost, compute_gradient, alpha, iterations, 0)

Iteration    0: Cost     2.66   
Iteration 1100: Cost     0.32   
Iteration 2200: Cost     0.30   
Iteration 3300: Cost     0.29   
Iteration 4400: Cost     0.28   
Iteration 5500: Cost     0.27   
Iteration 6600: Cost     0.26   
Iteration 7700: Cost     0.25   
Iteration 8800: Cost     0.25   
Iteration 9900: Cost     0.24   
Iteration 10999: Cost     0.23   


In [112]:
ypred3=predict(x,w,b)

In [113]:
print(ypred3)

[0.00464129 0.00456575 0.00386477 0.0047994  0.00452537 0.00792197
 0.00452973 0.00513184 0.00414286 0.00474401 0.00548717 0.00553236
 0.00415913 0.00265011 0.00414282 0.00652026 0.00498453 0.00499192
 0.00786903 0.00552418 0.00701966 0.00597014 0.00262041 0.00825156
 0.00783025 0.00587614 0.00666484 0.00531951 0.00476017 0.00547383
 0.00561391 0.00644    0.00480324 0.00486688 0.00474401 0.00365852
 0.00448441 0.00474401 0.00367073 0.0052376  0.00435528 0.00416997
 0.00363502 0.00766978 0.00943692 0.00481151 0.0057677  0.00425277
 0.0053764  0.00459214 0.44053117 0.37238748 0.51292259 0.19915663
 0.40967763 0.31168245 0.44001786 0.07209116 0.37846762 0.18003734
 0.09264593 0.2759984  0.1818771  0.39919029 0.13391748 0.34404691
 0.33710523 0.18959367 0.37426827 0.16194831 0.48618304 0.21533423
 0.48952642 0.36579604 0.29177853 0.34053485 0.46410365 0.56918342
 0.35679672 0.10269429 0.14480179 0.12285023 0.17661932 0.54812117
 0.32800284 0.36803878 0.44461868 0.31837002 0.21604942 0.1975

In [114]:
yfinal=[]
for i in range(0,len(ypred1)):
  if(ypred1[i]>ypred2[i] and ypred1[i]>ypred3[i]):
    yfinal.append("Iris-setosa")
  elif(ypred2[i]>ypred1[i] and ypred2[i]>ypred3[i]):
    yfinal.append("Iris-versicolor")
  elif(ypred3[i]>ypred1[i] and ypred3[i]>ypred2[i]):
    yfinal.append("Iris-virginica")
yfinal=np.array(yfinal)

In [115]:
print(yfinal)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor'
 'I

In [116]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(yoriginal,yfinal)
print(cm)
accuracy_score(yoriginal,yfinal)

[[50  0  0]
 [ 0 33 17]
 [ 0  0 50]]


0.8866666666666667